package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 22 мая 2019 г. 9:28:21 MSK
*/


/* =B5@D59A 107>2>9 AB0=F88 */
public interface StationOperations 
{

  /* 0@538AB@8@>20BL B@C1:C A =><5@>< phoneNum,
      4;O >1@0B=>3> 2K7>20 B@C1:8 8A?>;L7>20BL AAK;:C TubeCallback */
  int register (Cell.TubeCallback objRef, String phoneNum);

  /* B?@028BL A>>1I5=85 message >B =><5@0 fromNum : =><5@C toNum */
  int sendSMS (String fromNum, String toNum, String message);
} // interface StationOperations
