package Cell;


/**
* Cell/TubeCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 22 мая 2019 г. 9:28:21 MSK
*/


/* =B5@D59A >1@0B=>3> 2K7>20 B@C1:8 */
public interface TubeCallback extends TubeCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TubeCallback
